<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Verify.cs" />
    <PackageReference Include="BinaryKits.Zpl.Viewer" Version="1.3.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>
</Project>
